### ISSUE TITLE
Can't see message information

### ISSUE THREAD

**Issue by nickelghost** [PaperMtn/slack-watchman#50]
**Describe the bug**

Hi, I can't see any info (user, content) of the messages that are suspected. I haven't found any docs or additional options on it.

**To Reproduce**

```bash
docker run --rm --platform linux/x86_64 papermountain/slack-watchman --timeframe d --all --output json --cookie --debug --verbose
```

**Expected behaviour**

Information pointing to the message and its author included in the logs, as shown in a screenshot on the website.

![image](https://github.com/PaperMtn/slack-watchman/assets/16365643/4fb9977a-5b8f-424d-adfe-80955f0ff1e3)

**Actual behaviour**

No info about the message found in the logs.

```
{"timestamp": "2023-07-21 09:53:42,218", "level": "INFO", "message": "Searching for PII and Secrets"}
{"timestamp": "2023-07-21 09:53:42,219", "level": "INFO", "message": "Searching for posts containing Passwords"}
{"timestamp": "2023-07-21 09:53:43,338", "level": "INFO", "message": "1 potential matches found"}
{"timestamp": "2023-07-21 09:53:43,341", "level": "INFO", "message": "No matches found after filtering"}
{"timestamp": "2023-07-21 09:53:43,371", "level": "INFO", "message": "Searching for posts containing Twitter API Tokens"}
```

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by adam-moss** [comment]
I've observed the same behaviour.  I'm not convinced the de-dupe function, which as far as I can tell is the "filter", is not dropping results unintentionally.

**Comment by PaperMtn** [comment]
As far as I can tell, and from the tests i've run, things are working as expected. I think this might be some ambiguity with the output messages.

Due to the nature of how Slack searching works via the API. These are the steps taken:

 Slack Watchman uses a number of 'anchor' strings to find potential matches (the example you've posted, searching for [passwords](https://github.com/PaperMtn/watchman-signatures/blob/main/signatures/tokens_and_credentials/passwords.yaml), uses the strings `password`, `pwd` etc). Regex is then used to filter out to find matches that are hopefully (at least more likely to be) true positives

**Comment by PaperMtn** [comment]
@nickelghost As far as I can tell, and from the tests i've run, things are working as expected. I think this might be some ambiguity with the output messages.

Due to the nature of how Slack searching works via the API, you need to use a string value to return posts. These are the steps taken when Slack Watchman runs:

1. Slack Watchman uses a number of 'anchor' strings to find potential matches (the example you've posted, searching for [passwords](https://github.com/PaperMtn/watchman-signatures/blob/main/signatures/tokens_and_credentials/passwords.yaml), uses the strings `password`, `pwd` etc).
2. All messages returned by the Slack API for each anchor string are grouped together and deduplicated (to remove entries that are returned for multiple anchor strings). @adam-moss I can't see the issue you mentioned here, but i'm happy to be proven wrong if you've seen something else.
3. After deduplication, Slack Watchman outputs the number of **_potential_** matches that have been found after deduplication
4. Regex is then used to filter out to find matches that are hopefully (at least more likely to be) true positives.
5. Slack Watchman then outputs these **_actual_** matches as `total matches found after filtering`

Hopefully this explains it. Let me know if you still think there is something wrong.

**Comment by nickelghost** [comment]
Hi @PaperMtn , thanks for your reply. This indeed appears to be the case - I've added some test secrets to my Slack channels and I do get NOTIFY messages now.

Potential rejected messages being logged confused me there. Perhaps this behaviour could be changed (e.g. add "0 actual matches found") or documented so there is less confusion surrounding it?
